fixtures:
  repositories:
    "stdlib":
      "repo": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      "ref": "main"
    "concat":
      "repo": "https://github.com/puppetlabs/puppetlabs-concat.git"
      "ref": "main"
    "hocon":
      "repo": "https://github.com/puppetlabs/puppetlabs-hocon.git"
      # NOTE: module is archived, so not using "main"
      "ref": "master"
  symlinks:
    "puppet_authorization": "#{source_dir}"